#include<iostream>
#include<math.h>
using namespace std;
typedef long long ll;
//Triangular, pentagonal, and hexagonal
//
//Problem 45
//Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
//Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
//Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
//Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
//It can be verified that T285 = P165 = H143 = 40755.
//
//Find the next triangle number that is also pentagonal and hexagonal.

bool checkTriangle(ll no){
	ll a = sqrt(2 * no);
	if((a * (a + 1)) / 2 == no)
	{
		return true;
	}
	return false;
}

bool checkPentagonal(ll no){
	ll a = (sqrt(24 * no) / 6) + 1;
	if((a * (3 * a - 1)) / 2 == no)
	{
		return true;
	}
	return false;
}

bool checkHexagonal(ll no)
{
	ll a = sqrt(8 * no) / 4 + 1;
	if(a * (2 * a - 1) == no)
	{
		return true;
	}
	return false;
}

int main(){
	bool found = false;
	ll i = 40755;
	ll a = (sqrt(8 * i) / 4) + 1;
	while(!found)
	{
		a++;
		i = (a * (2 * a - 1));
		if(checkTriangle(i) && checkPentagonal(i) && checkHexagonal)
		{
			cout<<"Next Triangle no that is also Hexagonal and Pentagonal :: "<<i;
			found = true;
		}
	}
	return 0;
}

